### ISSUE TITLE
Implement brace matching highlight in the editor

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#103]
A very useful feature of pretty much every other editor and IDE around is a mechanism to highlight matching or signal mismatching braces while typing and navigating the text. Here is an example from the Eclipse Plugin's source code (Java editor):

![selection_010](https://user-images.githubusercontent.com/889291/43370522-412c8224-9378-11e8-8b23-8b2d754e0f42.png)

**Comment by mickaelistria** [comment]
This is typically provided by a language-configuration.json file which defines matching brackets, and Eclipse TM4E using it to enable such feature. So to solve this, we should probably find a good language-configuration.json file for Rust and just include and declare it in plugin.xml.

**Comment by norru** [comment]
I found this https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributeslanguages but it seems to be specific to Visual Studio Code.

**Comment by LucasBullen** [comment]
We can use the same language-configuration.json file as [rls-vscode](https://github.com/rust-lang-nursery/rls-vscode/blob/master/language-configuration.json).

However, we will only get [bracket closing](https://github.com/eclipse/tm4e/issues/132). Bracket matching is not implemented yet in tm4e (https://github.com/eclipse/tm4e/issues/141), but [an example](https://bugs.eclipse.org/bugs/show_bug.cgi?id=521031) of how todo this was created upsteam for the generic editor so it should not be too hard to implement.

Marking this issue as upstream for this reason.

**Comment by norru** [comment]
:(

It's not the same feature. In fact, speaking for myself, I would love bracket matching (for all types of parentheses) but I really loathe bracket autoclosing.

If you implement bracket autoclosing, please make sure it can be disabled.

**Comment by Boereck** [comment]
The language-configuration.json from rls-vscode is under Apache and MIT license. I Would not simply copy over their file. You probably have to start an IP process, filling out a Contribution Questionnaire etc. Since the file from aCute can be used for rust as well, I would use this as a starting point. This version already is EPL-2.0.
The rls-vscode version adds angle brackets to the "brackets" section, which I would not include (depending on how the bracket matching algorithm works). In VS Code the following code leads to angle bracket matching, which may be confusing:
```Rust
let i = 3;
if(i < 4) {
}
if ( i > 5) {
}
```

For some reason the rls-vscode language-configuration only auto-closes doc comments `/**` and `/*!` (see [here](https://doc.rust-lang.org/reference/comments.html#doc-comments)). I don't think this makes sense. We can auto-close `/*` the user can then continue with either `*` or `!` to create a doc comment, all types of comments end with a simple `*/` anyway.

The rls-vscode version auto-closes everything also in comments. For brackets and quotes this actually is often desirable, since code samples are often written in doc comments. However I have almost never encountered nested comments. So I would actually not auto-close `/*` in comments. This differs from the rules specified for C# in aCute.

**Comment by mickaelistria** [comment]
> The language-configuration.json from rls-vscode is under Apache and MIT
> license. I Would not simply copy over their file. You probably have to
> start an IP process, filling out a Contribution Questionnaire etc. Since
> the file from aCute can be used for rust as well, I would use this as a
> starting point. This version already is EPL-2.0.
>
Creating a CQ is a 3 minutes operation and for simple licenses like MIT or
Apache, it's checked automatically and approved in less than one hour
usually. So let's use the best file and the right process as it's not
really much more burden.

**Comment by LucasBullen** [comment]
This has now been implemented in TM4E and inherited in f32d634.
View the `TextMate > Language Configurations` for all the new features added with this patch. Also on that preference page you are able to enable/disable multiple features including bracket closing while keeping matching bracket highlighting.

**Comment by norru** [comment]
I have got this set up:

![image](https://user-images.githubusercontent.com/889291/45256702-17c23200-b392-11e8-9eb5-6556b4e27e0d.png)

- brace autoclose works (and I can disable it)
- brace highlight *does not work*
- comment/uncomment region *does not work* (after mapping it to a keystroke)

**Comment by norru** [comment]
After https://github.com/LucasBullen/corrosion/commit/ee0c05dc6ce1996b9d8a13eed04d92f6a6c24d76 also brace autoclose stopped working (opened separate issue)

**Comment by norru** [comment]
https://github.com/eclipse/tm4e/issues/179
