### ISSUE TITLE
Content assist makes no useful proposals

### ISSUE THREAD

**Issue by madmajestro** [eclipse/corrosion#117]
I don't get any useful completion proposals at all.

Example:
Actually i do my first steps learning rust and i simply tried to copy and paste the "hello world" project of the tokio.rs homepage. If i delete any ".unwrap()" at the line-endings i get only proposals like "for", "unimplemented", "unreachable"... but nothing useful like "unwrap()".

Im using the latest versions of eclipse photon, corrosion and rust (1.28.0).

Here is my LSP4E log, i hope it is helpful:

[org.eclipse.corrosion.rls.log](https://github.com/eclipse/corrosion/files/2320565/org.eclipse.corrosion.rls.log)

**Comment by mickaelistria** [comment]
Can you please try a more recent version of Corrosion with a more recent version of RLS (you should be able to upgrade RLS in the preferences) ? I think it's supposed to work better now.
@norru Since you're closer to RLS than I am, do you confirm it's better with more recent versions?

**Comment by norru** [comment]
It's certainly better than it was a few months ago, still a long way to go, but maybe it's enough for the OP?

**Comment by norru** [comment]
I've now got latest of pretty much anything and autocompletion hits and misses, but mostly misses.

```
org.eclipse.corrosion.rls to LSP4E:{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"E0609","message":"no field `effect_properties` on type `ofx::ImageEffectProperties`\n\nunknown field","range":{"end":{"character":21,"line":38},"start":{"character":4,"line":38}},"severity":1,"source":"rustc"},{"code":"E0308","message":"mismatched types\n\nexpected an array with a fixed size of 28 elements, found one with 29 elements\n\nnote: expected type `&[u8; 28]`\n         found type `&'static [u8; 29]`","range":{"end":{"character":34,"line":40},"start":{"character":5,"line":40}},"severity":1,"source":"rustc"}],"uri":"file:///home/nico/Projects/itadinanta/ofx-rs/examples/simple/src/simple_plugin.rs"}}
org.eclipse.corrosion.rls to LSP4E:{"jsonrpc":"2.0","method":"window/progress","params":{"done":true,"id":"progress_82","title":"Indexing"}}
```
![image](https://user-images.githubusercontent.com/889291/48874279-5c366900-edea-11e8-912e-7a3cb4878378.png)

**Comment by ctron** [comment]
Another example where things are not optimal:

![image](https://user-images.githubusercontent.com/202474/48890020-eb1da280-ee37-11e8-8ab5-15b1fcbf3f3d.png)

Having the templates/macros wouldn't hurt, if the types (`InvalidStatusCode`, `StatusCode`) came first.

**Comment by madmajestro** [comment]
Im using the newest versions now and I see some improvements. But it's far away from a good development-experience. Imho this is one of the most critical features if you want more developers to use corrosion.

**Comment by Boereck** [comment]
@madmajestro let me give you some background on this issue.

## Overview (TL;DR)
The completions are mostly provided by the RLS, the Rust Language Server, which is part of the rust toolchain and can be installed via the `rustup` tool. It provides most of the "smarts" behind corrosion, which includes code completion. The RLS uses the rust compiler internals for some things, but for code completion it internally relies on a tool called racer. This tool is trading speed of completion for correctness and completeness. So this is not exactly a corrosion issue, but an issue of the RLS, racer, and the rust compiler. The generic code templates and some macro-suggestions are always provided as completions by corrosion itself.

## RLS code completion status and future developments

The rust compiler is currently structured in a very classical way, and was not really intended to be used for tasks typically performed within IDEs. "Pulling out" information just for a given file or a location in a file is such a typical operation. This is why code completion based on compiler internals would be very slow at the moment. The racer tool on the other hand tries to not get all the details right (in fact gets it wrong a lot of times), but is at the moment the tool of choice for code completion by the RLS. This a known issue and a frequent point of critique towards the RLS.

To provide better and faster code completions backed by the compiler, the Rust compiler is currently in a state of massive refactoring. This would allow to query the compiler for certain information. I've once seen a talk on this issue, where the presenter speculated the new system would take a lot of time to implement and maybe be available towards end of 2019.

## What can/cannot/won't be done by corrosion?

Given the quality of content assist and the probably long time span for a high quality replacement, why doesn't corrosion implement its own code completion? 
Leaving aside the fact that corrosion does not have enough manpower to pull something like this off (and would require writing a lot of functionality already implemented in the RLS), I would even argue that betting on the RLS for has serious long term benefits:

- Updates for every new Rust release and it's language features are coming to corrosion on the day of the release. There is no delay for implementing language features in corrosion. And keep in mind that Rust releases a new version every six weeks.
- Since the RLS is the central tool for language support of many editors and IDEs, the community is bigger than the community of a single solution as corrosion. This will provide us new features "for free" at a higher rate.
- When the compiler refactoring is done, the better code completion is there for us, and probably better than what we would do

Also: The racer tool is also under active development and enhancements are to be expected in the future, even without the rust compiler refactoring.

So what can we do? I'd have to look into the sources, but I can imagine we could do something with regard to completion ordering. This would address @ctron s [issue](https://github.com/eclipse/corrosion/issues/117#issuecomment-440949057).

BTW: Most other Rust editors also use the RLS and will provide almost the same completions. The very idea of a language server is that you can choose the editor/IDE of your liking and get almost the same functionality. A notable exception is the IntelliJ Rust plugin, which may have better code completion (I have actually not tried it yet), but can only be used for debugging when used with the commercial CLion IDE.

**Comment by madmajestro** [comment]
@Boereck 
Many thanks for the detailed explanation. I wasn't aware of the exact architecture / technical details and i agree with you. In this case it doesn't make sense to spent much time in the development of a corrosion-specific solution for this problem. So i will keep an eye on the compiler and racer changes and try it again from time to time.

**Comment by ctron** [comment]
> So what can we do? I'd have to look into the sources, but I can imagine we could do something with regard to completion ordering. This would address @ctron s issue.

Maybe you could replicate what JDT is doing in this case. IIRC you can press Ctrl-Space multiple times to cycle through different providers of code completions. The first could be the RLS, the second could be the templates.

**Comment by mickaelistria** [comment]
That said, Corrosion provides a specific SnippetsContentAssistProcessor that may add to the confusion here.
I don't know much about what it provides, but it seems to me this would better bz handled inside RLS which is smart enough to not show templates where it doesn't make sense, while we don't really want Corrosion to implement, host and maintain such language-specific smartness.

**Comment by norru** [comment]
Update: I am actually starting to get useful autocompletion suggestions - but still nowhere near as polished as other languages supported by Eclipse.

**Comment by mickaelistria** [comment]
I'm closing this one. Please open specific tickets for specific completion issues; that will be easier to route to the LS.
