### ISSUE TITLE
New Project creates a project with errors

### ISSUE THREAD

**Issue by ctron** [eclipse/corrosion#160]
Creating a new project, creates a project with the following error for me:

~~~
found crate `std` compiled by an incompatible version of rustc

help: please recompile that crate using this compiler (rustc 1.30.0 (da5f414c2 2018-10-24))
note: the following crate versions were found:
      crate `std` compiled by rustc 1.29.1: /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-af9ed753d535e00e.rlib
      crate `std` compiled by rustc 1.29.1: /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-23c5a4e3162880bd.rlib
      crate `std` compiled by rustc 1.29.1: /usr/lib64/libstd-23c5a4e3162880bd.so
~~~

**Eclipse:**
Eclipse IDE for Eclipse Committers

Version: 2018-09 (4.9.0)
Build id: 20180917-1800

**Corrosion:**
Corrosion: Rust edition in Eclipse IDE	0.1.0.201809141024	org.eclipse.corrosion.feature.feature.group	Red Hat Inc.

**OS:**
RHEL 7.5

**Expectation:**
I would expect that a new project wizard creates a project that has no errors or warnings.

**Comment by Boereck** [comment]
Hey Jens, did you try calling `cargo new myprojectname` in the terminal? This looks more like a messed up Rust installation. Do you have rust installed via RHEL repos and then used rustup to install a more recent version of Rust?

**Comment by Boereck** [comment]
Aha, so you did press the "mess up" button 😉. As far as I remember, the button will install rustup and with it the latest stable toolchain for you. Rustup will install everything in your user home, while RHEL will install everything in the system directories. It appears that your user local cargo is invoked, but the system level std library is found. Maybe adjusting your PATH variable will help, or uninstall the system level Rust version.

**Comment by ctron** [comment]
Ok so uninstalling rust using `rpm -e` did the trick. I am not sure if I need the rust RPMs though.

I still think there should be some way, to manage this in a better way. Not sure though how.

**Comment by Boereck** [comment]
Distros usually install cargo and rustc, but not rustup and the RLS. Since the distros want to manage the version of rust, it is understandable they don't install rustup. The RLS is not 1.0 yet, so I doubt distros ship this part of the rust toolchain (you may look in the RHEL repositories if it can be installed separately).
You would usually use rustup to install the RLS component which is not installed by default. But since the distros don't ship rustup I would say the only viable way at the moment is to use a user local rust install with rustup. 
It is strange though that the two installations conflict and I do not know if this is the fault of rustup or the maintainer of the rust toolchain in the RHEL repos.

**Comment by Boereck** [comment]
By the way: You can select the location of Cargo, the RLS, and the 'sysroot' directly in the Corrosion options. This might enable you to use either the system Rust installation (provided it comes with the RLS) or the user local rust toolchain, possibly without problems ;)

**Comment by ctron** [comment]
> By the way: You can select the location of Cargo, the RLS, and the 'sysroot' directly in the Corrosion options. This might enable you to use either the system Rust installation (provided it comes with the RLS) or the user local rust toolchain, possibly without problems ;)

I tried to play around with those settings, without having any real clue on what to put in. I am kind of lost there.

**Comment by norru** [comment]
Hi @ctron, here's a snapshot of my setting so at least you may have an idea :)

I **always** use `rustup` to install and update the toolchains and mostly stay on the last non-broken Nightly - I strongly recommend you use `rustup` as well rather than using .rpm or .deb packages installed on system paths

**Comment by norru** [comment]
If you have not done so, the following *optional* components are also required by Corrosion:

`rustup component add rls-preview rust-analysis rust-src`

**Comment by mickaelistria** [comment]
@ctron Does this still happen with the 2019-06 RC2 candidate?

**Comment by ctron** [comment]
I can't reproduce it. I guess it is closed.
