### ISSUE TITLE
[regression] Hover and go to definition not working on .cargo entries (and general editor flakeyness)

### ISSUE THREAD

**Issue by norru** [eclipse/corrosion#244]
This is different from https://github.com/eclipse/corrosion/issues/123 as RLS logs show RLS is finding the references, it's just the Rust editor not reacting to them.

In general, the editors have been very flaky recently, with problems in color syntax and debugger, on top of this.

**Comment by mickaelistria** [comment]
We should revisit the inclusion of `.cargo` folder since LSP4E improved support for external files. We might be able to stop showing the `.cargo` folder and rely on LSP4E for hover and go to definition with better results.
One issue is really in the LSP spec, there is no clear way to declare whether a LS can be used for a given file. We need a breakthough on LSP spec here to cascade to LSP4E, RLS, Corrosion and others and make sure we have a generic way to handle such external files.

**Comment by norru** [comment]
@mickaelistria I've seen you have worked on the `IResource` front, which sounds good. I don't know about the internals. IIRC, I was told that the `.cargo` entries are automatically added to every RLS instance, and there is some work to figure out how to get rid of the overhead. However, this is barely WIP.

Within the existing model, shouldn't this just work out of the box? Why doesn't it?

**Comment by norru** [comment]
@mickaelistria bump?

**Comment by mickaelistria** [comment]
I'm not likely to fix it soon as my backlog on Eclipse Platform, LSP4E, TM4E and Wild Web Developer has higher priority.
If you can motivate anyone else to look at it, that would be helpful for the project. Onboarding new contributors would be high priority.

**Comment by norru** [comment]
No pressure then :D. I'll see what I can do.

**Comment by mickaelistria** [comment]
With your recent change for LSP4E, does it work any better?

**Comment by norru** [comment]
Works better with last LSP4E (2019-08-12). Reopen if necessary.

**Comment by norru** [comment]
> We should revisit the inclusion of .cargo folder since LSP4E improved support for external files.

LSP4E seems better in that respect, it's the Debug Adapter which is still playing up a bit.
