### ISSUE TITLE
Cannot auto-install Rustup from preference page

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#299]
I'm setting up a new machine where I don't have `rust` installed. I'm following the steps recommended by Corrosion. After installing `cargo` manually (as asked by the Cargo wizard), I could create a cargo project.
When opening editor, I see the popup asking me to go though Preferences to configure extra things (like rustup), on the preference page, I click "Install" and then get an error:
![Screenshot from 2020-01-29 18-07-03](https://user-images.githubusercontent.com/469058/73379767-27ae1f00-42c3-11ea-804a-5f154ed19545.png)

**Comment by Boereck** [comment]
I think you are using the last release, right? I think I fixed the issue with PR #281. Can you test this with the latest snapshot?

**Comment by mickaelistria** [comment]
Yes, I'm using latest release.
Updating to snapshot removes this error and I could use the script. However, it seems like it doesn't find the location of the rls.conf file. Indeed, the rls.conf file isn't in the usual location, and I couldn't find where it actually is to set it manually...

**Comment by Boereck** [comment]
The `rls.conf` file can be configured in the preferences.
![grafik](https://user-images.githubusercontent.com/919163/73450136-0d2c8200-4365-11ea-81df-8f680202a0c3.png)
But it actually is not needed, Corrosion will use a default if there is no conf file (which is the default). 

What message did you see? I think there should be an Info message in the log. Should be make this a warning or add an explanation that a default configuration is used if no config is present?

AFAIK the RLS team does not ship a config file anymore, we read it if it is present and configure the init-message to the RLS with it. It is a continuation to how the RLS was configured in the past, just now read by us instead of by the RLS itself.

**Comment by akurtakov** [comment]
If it's not needed and Corrosion works just fine without it - nothing should appear in the log. It's a common practice for products to ensure that on first start there is nothing in the error log - no matter warning/info/error.

**Comment by Boereck** [comment]
Then we should either 
* have a check box if a config file is used at all
* or initialize an empty text box and handle this as no config file

Because if someone configures a config file and this is non-existent, I would expect a message in the log.

**Comment by akurtakov** [comment]
On Thu, Jan 30, 2020 at 2:52 PM Max Bureck <notifications@github.com> wrote:

> Then we should either
>
>    - have a check box if a config file is used at all
>    - or initialize an empty text box and handle this as no config file
>
> Because if someone configures a config file and this is non-existent, I
> would expect a message in the log.
>

Sounds like it. Pointing to non-existing file should be logged. Maybe we
can just check whether the config is empty string and not log in this case?

**Comment by Boereck** [comment]
Sure, I would also omit trying to read the file on an empty string. Should not be that complicated to implement.

**Comment by norru** [comment]
I originally implemented this, and the log warning was bothering me to no end :D Thanks for fixing!
