### ISSUE TITLE
Import Rust project

### ISSUE THREAD

**Issue by MaSven** [eclipse/corrosion#33]
Now i can only open an rust project over the 

> Open Projects from Filesystem ...

But i can not import an rust project like other projects in eclipse as example maven,gradle etc.
It would help, if there were an import option for rust projects into the workspace.

**Comment by LucasBullen** [comment]
Great idea! Currently in the middle of moving the Corrosion project to Eclipse, so addressing this issue will have to wait until the move. However, if you feel up to it, feel free to make a PR.

**Comment by MaSven** [comment]
I will try to implement this. Iam still new to Eclipse Plugin development so it will take some time for me.

**Comment by LucasBullen** [comment]
Great to hear, if you have any questions feel free to ask.

**Comment by mickaelistria** [comment]
What makes a regular vanilla project a Rust project in Corrosion? Must a Rust project have a dedicated nature? Or some dedicated builders? If yes, then it would indeed make sense to have the import detecting existence of .rs files to automatically configure the project.
The entry-point for this feature is the extension point `org.eclipse.ui.ide.projectConfigurators`.
But in general, the less configuration a project needs to work, and the happier maintainers and users will be ;) Maven and Gradle are not very good example as they require a lot of configuration to work, if Corrosion can avoid that, it would make things simpler.

**Comment by MaSven** [comment]
I was just thinking about supporting cargo projects. But a single file would be possible too.

**Comment by LucasBullen** [comment]
I agree that it would be a cargo project importer. It would have to add the [Cargo builders](https://github.com/eclipse/corrosion/tree/master/org.eclipse.corrosion/src/org/eclipse/corrosion/builder) (an example of this being done can be found in the [new project wizard](https://github.com/eclipse/corrosion/blob/master/org.eclipse.corrosion/src/org/eclipse/corrosion/wizards/newCargo/NewCargoProjectWizard.java#L209)) and ensure that it has a `Cargo.toml` file so that these projects pass the [CargoProjectTester](https://github.com/eclipse/corrosion/blob/18b93720e2462d47762dde7eebd3ae65c9978d1c/org.eclipse.corrosion/src/org/eclipse/corrosion/CargoProjectTester.java#L20) and can be run.

**Comment by LucasBullen** [comment]
@MaSven Could you confirm that PR #55 works with importing rust projects? If it all works I think we can call this issue done without adding an importer that does the same as a standard importer.

**Comment by MaSven** [comment]
Seems to work for me. I did an import in general with existing from fodler or archive and it detected it as  project.

**Comment by LucasBullen** [comment]
Issue fixed with c0a057b
