### ISSUE TITLE
Debugging under Windows Eclipse 2020-09 (4.17.0) forces install of dated toolchain 1.41.0-x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by gbuehler2063** [eclipse/corrosion#340]
When I run a Rust project in a Debug configuration, an old tool-chain "1.41.0-x86_64-pc-windows-msvc" is installed automatically before starting the exe-File. 
The debugger does not work anyway (no breakpoints accepted) but the exe is run in the Eclipse console. 
After the exe terminated, there is a pop-up-Dialog, saying: 

> "Could not determine GDB version using command: <USERDIR>\.cargo\bin\rust-gdb.exe --version
> error: the 'rust-gdb.exe' binary, normally provided by the 'rustc' component, is not applicable to the 'stable-x86_64-pc-windows-gnu' toolchain "
> 

However, I wanted to use the current stable version which is rustc 1.47.0 (18bf6b4f0 2020-10-07).
The toolchain was installed using rustup and I pointed to the install directory of rustup and cargo as well as rls in the Preferences/Rust Dialog.

My Eclipse is the current version: 2020-09 (4.17.0) on an up-to-date Windows 10 Pro.
Corrosion is installed from the Marketplace and up to date:   Corrosion: Rust edition in Eclipse IDE	1.0.0.202009030945

**Comment by mickaelistria** [comment]
@akurtakov Are you familiar with cargo here to know why would an incompatible version of rust-gdb.exe be installed?

**Comment by akurtakov** [comment]
So where does this old tool-chain comes from? If I'm to guess it's prior to the stable one on the PATH env variable. I would look for it and remove it.

**Comment by mickaelistria** [comment]
@gbuehler2063 any progress?

**Comment by mickaelistria** [comment]
No news, let's close.
@gbuehler2063 please reopen with more details to reproduce using latest snapshots if you still face this issue.

**Comment by tasogare3710** [comment]
> @akurtakov Are you familiar with cargo here to know why would an incompatible version of rust-gdb.exe be installed?

Read the error message, it seems that the 1.41.0-x86_64-pc-windows-msvc toolchain is not used, but the stable-x86_64-pc-windows-gnu toolchain is used, so it is not directly related to this issue.

> error: the 'rust-gdb.exe' binary, normally provided by the 'rustc' component, is not applicable to the 'stable-x86_64-pc-windows-gnu' toolchain "

This error message is a common error message for rustup wrappers when the required components are not installed. Therefore, this issue is equivalent to the issue described in [this page](https://github.com/eclipse/corrosion/blob/master/documentation/Troubleshooting.md#debugging-on-windows). In other words, windows does not have the trust-gdb shell script, but [this](https://github.com/rust-lang/rustup/issues/2838#issuecomment-939268993) is also a known issue.
