### ISSUE TITLE
Stuck at "Downloading rust-analyzer... {0}%"

### ISSUE THREAD

**Issue by rootkea** [eclipse/corrosion#373]
Hello!

I have installed Corrosion: Rust edition in Eclipse IDE 1.2.0.202103130942 installed on Eclipse 2021-03 (4.19.0).

Whenever I click on "Download rust-analyzer" it gets stuck on "Downloaing rust-analyzer... {0}%" without no progress. I also see "Input stream must be configured" and "Unhandled event loop exception" error messages in error log.

Thanks!

**Comment by mvvvv** [comment]
Got the same problem today :
Install rls with rustup : 
`rustup +nightly component add rust-analyzer-preview`

the path will be  ~/.cargo/bin/rls

I've uninstalled ubuntu rustc package too to use rustup only.

**Comment by mickaelistria** [comment]
Rust-Analyzer artifact location changed recently to emphasize x86_64 vs aarch64.
Corrosion needs to be update to the new locations. Would one of you be interested in submitting a fix to https://github.com/eclipse/corrosion/blob/master/org.eclipse.corrosion/src/org/eclipse/corrosion/RustManager.java#L319 in order to use new artifact names (see https://github.com/rust-analyzer/rust-analyzer/releases/ )?

**Comment by rootkea** [comment]
Sure! I'll submit the PR later in the evening.

**Comment by mickaelistria** [comment]
Fixed with #373. This should be available in snapshots ( http://download.eclipse.org/corrosion/snapshots/ ) within a few minutes.
