### ISSUE TITLE
"Problems" view shows errors for every line of `.toml` files.

### ISSUE THREAD

**Issue by hydra** [eclipse/corrosion#383]
Hi,

For every `Cargo.toml` file the "Problems" view has the an entry for every line of the file, like this:

![image](https://user-images.githubusercontent.com/57075/133271283-7391d500-8a5d-4928-8c64-d9abe590e8ef.png)

The `.toml` file was auto generated by `cargo new hello-world`

```
[package]
name = "hello-world"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
```

```
  Eclipse IDE for Embedded C/C++ Developers	4.21.0.20210902-1200	epp.package.embedcpp	Eclipse Packaging Project
  Corrosion: Rust edition in Eclipse IDE	1.2.1.202106081156	org.eclipse.corrosion.feature.feature.group	Eclipse Corrosion
```

**Comment by akurtakov** [comment]
I can reproduce the issue. Meanwhile please use https://download.eclipse.org/corrosion/snapshots/ as there is a fix to make it work with latest lsp4j commit a1e99f1357cbf7be5b37d6866e3056c0c742dca1

**Comment by mickaelistria** [comment]
I think the issue may be that now that rust-analyzer is the default, there is no more support for .toml; but the LS is still associated with .toml files (legacy of RLS), and assumes these .toml files are to be parsed as Rust files.
The following actions could be tried:
* Unassociate the `org.eclipse.corrosion.rls` (which is now rust-analyzer despite the name) from `org.eclipse.corrosion.cargo.manifest` content-type
* Verify the issue happens because of rust-analyzer and report issue here: rust-analyzer should probably at least not send diagnostics for files it cannot process; or it should support cargo manifest files.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/corrosion/pull/388

**Comment by mickaelistria** [comment]
Please try https://download.eclipse.org/corrosion/snapshots/ and reopen if it doesn't fix this issue.

**Comment by hydra** [comment]
@mickaelistria Just  tried with latest release of Eclipse 2019-09 and the snapshot version as below and the list of problems has gone now.

```
Corrosion: Rust edition in Eclipse IDE	1.2.2.202109281422	org.eclipse.corrosion.feature.feature.group	Eclipse Corrosion
```

Thanks for the fix.  Do you know when this will be included in a non-snapshot release?
