### ISSUE TITLE
Ctrl+Space doesn't work for Corrosion EPP when editor is open for the 1st time

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/corrosion#60]
Using EPP package from https://ci.eclipse.org/packaging/job/photon.epp-tycho-build/lastSuccessfulBuild/artifact/org.eclipse.epp.packages/archive/

Ctrl+Space doesn't work as it doesn't trigger content-assist. Looking in Quick-Access/Ctrl+3, I don't even see the generic content assist command available. I believe the package misses a handler for this command.

**Comment by mickaelistria** [comment]
I cannot reproduce it now (Good news!)

**Comment by mickaelistria** [comment]
I'm reopening, I can reproduce it on first startup of the editor. Closing editor and reopening it makes completion work again. I guess the issue could be in LSP4E, but let's track it here at the moment until better qualified for LSP4E.

**Comment by pierlauro** [comment]
Is it showing "Computing symbols" in the outline panel when not working?

**Comment by LucasBullen** [comment]
Some further debugging
 - Only happens when you have an editor open at startup
   - Works when creating a new project and when you open a file, but not if you have a file open, close the IDE and reopen it
 - Is not related to having the snippet completion
    - Tested removing it and does not affect the problem
 - Completion from auto-activation characters (`.` and `:`) is active so only the `Ctrl + Space` handler is missing

**Comment by mickaelistria** [comment]
> Only happens when you have an editor open at startup
>     Works when creating a new project and when you open a file, but not if you have a file open, close the IDE and reopen it

Seems like an issue in Generic Editor or LSP4E then.

**Comment by mickaelistria** [comment]
I can't reproduce it with recent versions of everything.
