### ISSUE TITLE
Open definitions/files from the external crates

### ISSUE THREAD

**Issue by dc740** [eclipse/corrosion#80]
This is something I was used to abuse when using RustDT.
If you tried to go to a definition and Ctrl+Clicked on it from your project, it would simply open the file that contained it and took you to the definition, even when the file was in an external crate, and it was not part of the project. It was not always available (it never took me to the rust source, only to external crates), but it was very useful.

**Comment by mickaelistria** [comment]
Ctrl+Space delegate to RLS Go To Definition to select which file to show. I believe this is a missing feature in RLS. I opened https://github.com/rust-lang-nursery/rls/issues/884

**Comment by LucasBullen** [comment]
Seems to be fixed in Nightly, working with Stable get a response to a non-existing file, while Nightly has it fixed and opens the file.

@dc740, can you confirm this issue is fixed by going to the preferences and choosing the Nightly or a different toolchain, I also found I had to close the project and reopen it after switching the toolchain before the problem went away. 

Test code: ` let start: Ratio<BigInt> = Ratio::from_integer(FromPrimitive::from_u64(number).unwrap());`
Doing a Ctrl+Click on `unwrap()`

LSP4E to org.eclipse.corrosion.rls:
```
 {"jsonrpc":"2.0","id":"41","method":"textDocument/definition",
"params":{"textDocument":{"uri":"file:///home/lbullen/eclipseWorkspaces/rustIDE1/new_rust_project/src/main.rs"},
"uri":"file:///home/lbullen/eclipseWorkspaces/rustIDE1/new_rust_project/src/main.rs",
"position":{"line":6,"character":84}}}
```
Stable org.eclipse.corrosion.rls to LSP4E:
```
{"jsonrpc":"2.0","id":41,
"result":[{"uri":"file:///home/lbullen/eclipseWorkspaces/rustIDE1/new_rust_project/libcore/option.rs",
"range":{"start":{"line":331,"character":11},"end":{"line":331,"character":17}}}]}
```
(there is no libcore folder in the project directory)

Nightly:
```
{"jsonrpc":"2.0","id":26,
"result":[{"uri":"file:///home/lbullen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/option.rs",
"range":{"start":{"line":341,"character":11},"end":{"line":341,"character":17}}}]}
```
(correct file and opens in editor)

**Comment by LucasBullen** [comment]
Also Emilio, unrelated to this bug report I was wondering if I could grab your email address to talk off-github about getting some feedback from you about Corrosion. Either reply with your address or send me a message at lbullen@redhat.com. Thanks.

(@dc740  username for ping)

**Comment by dc740** [comment]
Thanks for the info. I haven't used rust in a couple of weeks but I tried this and it looks like it works as you described.
I'll keep using nightly for RLS to avoid this issue.

Are there any estimates about when this will be available in Stable? 

Thank you.

**Comment by mickaelistria** [comment]
> Are there any estimates about when this will be available in Stable?

That's not something we can control from corrosion, as it's fully in RLS and Corrosion doesn't include RLS (uses rustup+Cargo to get it from the preference page). So we cannot really provide an estimate here. Sorry.

I'm closing this issue because it's fixed in RLS nightly and there is nothing to change in Corrosion.
Thanks for your report!
